### ISSUE TITLE
Strange attachment names when parsing some .msg files

### ISSUE THREAD

**Issue by vhanzu** [Sicos1977/MSGReader#391]
I am using the nuget package in c# and I was parsing some msg file from a customer, no extra details.

 var reader = new MsgReader.Reader(); 
 var outputFiles = reader.ExtractToFolder(fileName, outputFolder);

The result contains some ugly attachment names:
![image](https://github.com/Sicos1977/MSGReader/assets/125655014/df299a8c-7fc1-4a21-89b1-e7f93cd15611)

But it should be like these:
![image](https://github.com/Sicos1977/MSGReader/assets/125655014/5d40d4bf-d9ad-4f84-808d-e8771b2d34c6)

Most likely the issue in in the Attachment constructor where the MapiTags.PR_ATTACH_LONG_FILENAME is considered as most relevant for reading the attachment name. But in my opinion MapiTags.PR_DISPLAY_NAME should be more relevant as this is the one getting displayed to the user.

Unfortunately, I can't attach the msg file causing the issue.

**Desktop (please complete the following information):**
 - OS: w10 LTSC build 17763

**Comment by Sicos1977** [comment]
Uh.... I think I fixed this.. if not then please reopen this issue.

**Comment by vhanzu** [comment]
I've just retested with the latest nuget, version 5.5.5.0, MsrReader.dll date 17.01.2024 and the problem still reproduces.

![msgreader nuget package](https://github.com/Sicos1977/MSGReader/assets/125655014/bc2cc13c-4246-4402-be8e-ef6e1c81f3ac)

Unfortunately, I can't reopen the bug because there is no Reopen button available.

**Comment by Sicos1977** [comment]
I reopened the issue... thought that I had fixed this but apperently not... I'll try to look into this, this week.

**Comment by Sicos1977** [comment]
Can you resent me the file that is giving this issue? I know that you sent it before but I can't find this msg file anymore. Please zip the file before sending it to sicos2002@hotmail.com

**Comment by vhanzu** [comment]
[Bestellung 4500745288.zip](https://github.com/Sicos1977/MSGReader/files/14957018/Bestellung.4500745288.zip)

**Comment by Sicos1977** [comment]
I did receive your e-mail but didn't have the time to look into it... I try to do it this weekend.
