### ISSUE TITLE
Subject special characters not properly displayed in .NET 8 (worked in .NET Framework 4.7.2) - same MSGReader version

### ISSUE THREAD

**Issue by summerkitsune** [Sicos1977/MSGReader#398]
**Describe the bug**
When you read an .msg Subject with MSGReader **in a.NET 8 project**, it fails to properly display special characters, and that is not what happens in the .NET Framework 4.7.2 project. In the latter, it works. **Same MSGReader version**.

**To Reproduce**
I created 2 repositories that contain basically the same code (and same dependencies) - the only difference between these 2 repositories being the .NET versions. The version of MSGReader is the same

Links to the repositories:

- [.NET 8 repository](https://github.com/summerkitsune/msg-reader-net8)
- [.NET Framework 4.7.2 repository](https://github.com/summerkitsune/msg-reader-net472)

The 2 repositories use the same .msg file (same md5 checksums). You can find the .msg file in the repositories.

The <kbd>.msg</kbd> file has been created like this:

- Create an email in Outlook with special characters in its Subject text
- Save as .msg file (not Unicode)

**Expected behavior**
I expected the special characters to be displayed properly, like in the .NET Framework 4.7.2 project.

**Screenshots**
![image](https://github.com/Sicos1977/MSGReader/assets/15868647/e125481c-2a8f-47df-8493-f36182301b2a)

**Desktop**
 - OS: Windows 11
 - Problem reproducible in a Console App
 - Version: MSGReader version 5.5.5 (latest version at the time of writing).

I have this problem on my machine but I've also tried on another machine (still Windows) with the same results.

**Additional context**
I encountered this problem while migrating a project from .NET Framework 4.7.2 to .NET 8.

**Comment by Sicos1977** [comment]
Did you register the encoding providers?

**Comment by Sicos1977** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.text.encoding.registerprovider?view=net-8.0

**Comment by Sicos1977** [comment]
https://www.nuget.org/packages/System.Text.Encoding.CodePages/

**Comment by Sicos1977** [comment]
This is something that works by default on the .net framework but is something you have to do yourself on other frameworks because they are cross platform.

**Comment by summerkitsune** [comment]
Thanks for your prompt answer :)

I think I had tested that, but I tried again just now:

![image](https://github.com/Sicos1977/MSGReader/assets/15868647/e9167c8f-4ac0-4e3a-b0fe-96fcd94f2bc2)
![image](https://github.com/Sicos1977/MSGReader/assets/15868647/ef95bda0-07eb-42fc-8695-f687d6188e23)

I then cleaned my solution and rebuilt, and then ran it again:

![image](https://github.com/Sicos1977/MSGReader/assets/15868647/62a8ddf8-944c-4bf5-b9e5-423ae2d73561)

**Comment by Sicos1977** [comment]
I never used MSGReader in .net8 so I'm a little bit blank about how to solve problems on this version of .net

You could try looking into  this file --> https://github.com/Sicos1977/MSGReader/blob/master/MsgReaderCore/Rtf/Document.cs

And set a break-point on this line --> if (byteBuffer.Count > 0 && reader.TokenType != TokenType.EncodedChar)

And than look if the chars get decoded correctly

**Comment by summerkitsune** [comment]
Thanks, I will do that ^^

**Comment by Sicos1977** [comment]
And did you solve it?

**Comment by summerkitsune** [comment]
Hi again, yes I found out why I am having this issue

Encoding.Default is Encoding.UTF8 or Encoding.Unicode in NET Core/3/4/5/6/7/8.
In .NET Framework, Encoding.Default is the system's active code page.

In .NET 8, It decoded badly the message subject of ANSI messages because it was no longer using the system's active code page by default, but trying to directly decode using Encoding.Unicode.
Decoding ANSI to Unicode leads to have these unrecognized characters in the string

I have forked your project, and added a fix on a branch created on the (commit) flag 5.5.5 (last release)
You can find the proposed commit [here](https://github.com/summerkitsune/MSGReader/commit/c2e9058ee4349e954a2361139aacc892fab0a431) 

I have added 2 unit tests that cover this and ran successfully all other tests (in net62 and net8)

![image](https://github.com/Sicos1977/MSGReader/assets/15868647/594b6923-144a-4e81-a397-24dbfa3c1fae)

**Comment by Sicos1977** [comment]
Nice you found it out... I also did not knew that Encoding.Default in net core defaults to UT8

**Comment by summerkitsune** [comment]
I'm not sure 100% if the way I fixed this is the _best_ way to do it, probably .NET Framework users don't need this fix, also this fix depends on UTF.Unknown to detect the encoding so it is possible we could break .NET Framework user experience by trying to decode by default with that library

I thought that we could maybe wrap the "detection" part with a preprocessor directive (only doing it for 'netstandard' users)

**Comment by Sicos1977** [comment]
Is it possible for you to sent me this msg file so that I can look into it to figure out a solution that works in both .net framework and newer versions? If so than please ZIP the MSG file before sending it to sicos2002@hotmail.com

**Comment by summerkitsune** [comment]
Hi, I sent you an email with what you asked

**Comment by Sicos1977** [comment]
Thanks... I'll will look into it an try to figure out a solution that will work on all .net versions

**Comment by summerkitsune** [comment]
Hi Kees, have you had time to figure out a solution?

**Comment by Sicos1977** [comment]
> Hi Kees, have you had time to figure out a solution?

Sorry but totally forgot this issue... to busy with another project at the moment. I'll give it a new try this weekend.

**Comment by summerkitsune** [comment]
Hi Kees, have you had the occasion to give it a try?

**Comment by Sicos1977** [comment]
This should be fixed in version 5.5.8, it is now using the MessageCodePage property to determine the used coding. It should probably always have been like this.

Sorry for the long delay but I was to busy with other things and kept finding issues to ignore this problem :-)

**Comment by synectics-agent** [comment]
@Sicos1977 Our scenario is still not working. We have an email in msg format which contains greek characters in the body. We are retrieving the body through the BodyHtml property and the encoding for most words is wrong. I could email you the sample msg file if you can take a look into this.

![image](https://github.com/Sicos1977/MSGReader/assets/89775570/569a8fcc-7404-49a4-90ea-8615bbaa1ef7)

**Comment by andhadj** [comment]
@Sicos1977  Our scenario is still not working. We have an email in msg format which contains greek characters in the body. We are retrieving the body through the BodyHtml property and the encoding for most words is wrong. I could email you the sample msg file if you can take a look into this.

![image](https://github.com/Sicos1977/MSGReader/assets/14963529/18b1188f-d370-453e-9ad7-b97c431d6134)

**Comment by Sicos1977** [comment]
This is probably another encoding issue that has nothing todo with the issue of the original poster because that issue is solved. I guess this is some kind of encoding problems that happens when the HTML is extracted from RTF but to be sure I have to see this message. If possible then ZIP the msg file and sent it to sicos2002@hotmail.com
