### ISSUE TITLE
non-English  msg file issues

### ISSUE THREAD

**Issue by Rectar** [Sicos1977/MSGReader#45]
I've parsed non-English msg files and then message shown as marks or ??.

for example:
msg files in MsgReadzip\MsgRead\bin\Debug\Inbox  shows：

```
Chinese part ¡
ÁÅ¤¤¦Ã

Japanese part ¡


fullwidth ¡
¢¢¢¡¢¢¢¢¢¡¢¢¡¢¢¢
```
I've tried  `MsgReader.Reader.ExtractMsgEmailBody(sr, false, "text/plain");` but still.

Please help.
thanks

[MsgRead.zip](https://github.com/Sicos1977/MSGReader/files/647915/MsgRead.zip)

**Comment by Sicos1977** [comment]
Can you send me the original MSG file so that I can test what is going wrong? Please zip the msg file before sending it to sicos2002@hotmail.com

Greetings,
Kees van Spelde

**Comment by daifutianjin** [comment]
Hi,
I meat the same issue.
I research it. the issue is in DomDocument.cs.  I fixed it.
												
`												// If we have a double byte charset like chinese then store the value and wait for the next HEX value
												if (hexBuffer == string.Empty)
													hexBuffer = reader.CurrentToken.Hex;
												else
												{
                                                    // Append the second HEX value and convert it
                                                    byte[] buff = new byte[] {
                                                        byte.Parse(hexBuffer,System.Globalization.NumberStyles.HexNumber),
                                                        byte.Parse(reader.CurrentToken.Hex,System.Globalization.NumberStyles.HexNumber)
                                                    };
                                                    stringBuilder.Append(encoding.GetString(buff));
                                                    // Empty the HEX buffer
                                                    hexBuffer = string.Empty;
												}
`.
Please try it. @Sicos1977 @Rectar

**Comment by Sicos1977** [comment]
Thanks for fixing, I will merge your code in the MSGReader this evening and if my test goes well then also publish it to NuGet

**Comment by Sicos1977** [comment]
I added the fix and pushed it to GitHub... can you please try it out if it works now?

**Comment by Rectar** [comment]
I've try some msg files, it works good. 
But some msg files with many words still happen in some part.

For this sample file , most of chinese show correctly , but there're some words still show incorrectly:
> n?F?誚 鞊d?º 
KONG-REY  102/8/27~8/29 

I've try this :https://github.com/logankp/Deliverance
but never meet this issue(although i can't open many msg files by this).

Sorry for replying late, my computer was broken that took much time on it.
[typhon.zip](https://github.com/Sicos1977/MSGReader/files/662937/typhon.zip)

**Comment by Sicos1977** [comment]
Hi,

I think I fixed the issue. Can you get the latest source from GitHub and try it out please?
Can you also please run some more test cases since it is hard for me to test with Chinese texts because I can't read it :-)

Greetings,
Kees van Spelde

**Comment by daifutianjin** [comment]
Part string still incorrectly. 
Continue change the file DomDocument.cs.
replace "encoding = font.Encoding ?? _defaultEncoding;" with "encoding = _defaultEncoding;".
All of the Chinese string will be OK.

**Comment by Rectar** [comment]
@daifutianjin awesome!
I tried some Japanese ,Korean,full-width words and work great too!

**Comment by Sicos1977** [comment]
Good to hear, I will make a new nuget package this evening and publish it (8:33 am overhere now :-) ).

**Comment by Sicos1977** [comment]
A new package has been published to NuGet
